name: build_and_test
on: push
jobs:
  do_all:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes ninja-build g++ python3 pip
          pip install conan~=2.0
      - name: setup conan project
        run: |
          conan profile detect
          conan install --output-folder ${{github.workspace}}/build --build missing ${{github.workspace}}
      - name: configure cmake
        run: cmake -B ${{github.workspace}}/build -GNinja -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
      - name: build
        run: cmake --build ${{github.workspace}}/build
      - name: run unit tests
        run: ctest --test-dir ${{github.workspace}}/build
      - name: install component tests dependencies
        run: pip install --requirement testing/requirements.txt
      - name: run all component tests
        working-directory: ${{github.workspace}}/testing
        run: pytest -v
