name: build_and_test
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes ninja-build g++ python3 pip
          pip install conan
      - name: setup conan project
        run: |
          conan profile new --detect default
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install --install-folder ${{github.workspace}}/build --build missing ${{github.workspace}}
      - name: configure cmake
        run: cmake -B ${{github.workspace}}/build -GNinja
      - name: build
        run: cmake --build ${{github.workspace}}/build
  # test:
  #   needs: build
  #   runs-on: ubuntu-22.04
  #   steps:
